// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5-ZVDQbMu2DN6gtxPXZLqU69OtT5XYHs',
    appId: '1:216515425863:web:8d50723760ec946e566362',
    messagingSenderId: '216515425863',
    projectId: 'mynotes-3234b',
    authDomain: 'mynotes-3234b.firebaseapp.com',
    storageBucket: 'mynotes-3234b.firebasestorage.app',
    measurementId: 'G-9MX9DF9FMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX2l5gPC-5hvQ0Q_n0UbsYUSyDYERATx0',
    appId: '1:216515425863:android:04335622497d308f566362',
    messagingSenderId: '216515425863',
    projectId: 'mynotes-3234b',
    storageBucket: 'mynotes-3234b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtV1ZKNE5H-QrEe0o6pGMtSKr1UfuVtQY',
    appId: '1:216515425863:ios:1b52e00d312e5461566362',
    messagingSenderId: '216515425863',
    projectId: 'mynotes-3234b',
    storageBucket: 'mynotes-3234b.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtV1ZKNE5H-QrEe0o6pGMtSKr1UfuVtQY',
    appId: '1:216515425863:ios:1b52e00d312e5461566362',
    messagingSenderId: '216515425863',
    projectId: 'mynotes-3234b',
    storageBucket: 'mynotes-3234b.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5-ZVDQbMu2DN6gtxPXZLqU69OtT5XYHs',
    appId: '1:216515425863:web:cd225e06ba43b36b566362',
    messagingSenderId: '216515425863',
    projectId: 'mynotes-3234b',
    authDomain: 'mynotes-3234b.firebaseapp.com',
    storageBucket: 'mynotes-3234b.firebasestorage.app',
    measurementId: 'G-7DHQGT1TWJ',
  );
}
